import { StyleSheet, Dimensions } from 'react-native'
import { COLORS } from './colors'

const { width } = Dimensions.get('window')

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.CREAM },
  content: { paddingHorizontal: 20, paddingBottom: 120 },
  pageTitle: { fontSize: 28, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE, marginBottom: 20 },

  // Auth
  authMain: { flex: 1, backgroundColor: '#FFF' },
  authScroll: { padding: 30, alignItems: 'center' },
  authGlow1: { position: 'absolute', width: 200, height: 200, borderRadius: 100, backgroundColor: COLORS.YELLOW + '15', top: -50, left: -50 },
  authGlow2: { position: 'absolute', width: 250, height: 250, borderRadius: 125, backgroundColor: COLORS.RED + '10', bottom: -100, right: -50 },
  authBrand: { alignItems: 'center', marginTop: 20, marginBottom: 30 },
  authLogoLarge: { width: 190, height: 190, resizeMode: 'contain' },
  authTagline: { fontSize: 10, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE, letterSpacing: 2.2, marginTop: -15 },
  authTitle: { fontSize: 26, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE, textAlign: 'center' },
  authSubtitle: { fontSize: 13, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, textAlign: 'center', marginTop: 10, paddingHorizontal: 20 },
  authForm: { width: '100%', marginTop: 30 },
  authInputWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderWidth: 1, borderColor: '#CBD8E5', borderRadius: 15, paddingHorizontal: 15, marginBottom: 15 },
  authTextInput: { flex: 1, paddingVertical: 14, paddingHorizontal: 10, fontFamily: 'Poppins_400Regular', color: COLORS.BLUE },
  authOptions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 25 },
  remember: { flexDirection: 'row', alignItems: 'center' },
  rememberText: { fontSize: 11, fontFamily: 'Poppins_500Medium', color: COLORS.BLUE, marginLeft: 5 },
  forgot: { fontSize: 11, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE },
  authSubmit: { flexDirection: 'row', backgroundColor: COLORS.BLUE, borderRadius: 20, paddingVertical: 16, justifyContent: 'center', alignItems: 'center', elevation: 3 },
  authSubmitText: { color: '#FFF', fontSize: 16, fontFamily: 'Poppins_700Bold', marginRight: 10 },
  authSep: { flexDirection: 'row', alignItems: 'center', marginVertical: 25 },
  line: { flex: 1, height: 1, backgroundColor: '#CBD8E5' },
  sepText: { marginHorizontal: 15, color: '#CBD8E5', fontSize: 12 },
  googleBtn: { borderWidth: 1, borderColor: '#CBD8E5', borderRadius: 20, paddingVertical: 14, width: '100%', alignItems: 'center' },
  googleTxt: { color: COLORS.BLUE, fontFamily: 'Poppins_600SemiBold', fontSize: 14 },
  switchAuth: { marginTop: 25 },
  switchText: { fontSize: 13, color: COLORS.TEXT_MUTED, fontFamily: 'Poppins_400Regular' },
  switchLink: { color: COLORS.BLUE, fontFamily: 'Poppins_700Bold' },

  // Home
  homeHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 30, marginBottom: 20 },
  userSection: { flexDirection: 'row', alignItems: 'center' },
  avatarHeader: { width: 44, height: 44, borderRadius: 22 },
  greetingText: { fontSize: 20, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE, marginLeft: 12 },
  notifBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', elevation: 2 },
  notifDot: { position: 'absolute', top: 12, right: 12, width: 7, height: 7, borderRadius: 3.5, backgroundColor: COLORS.RED, borderWidth: 1.5, borderColor: '#FFF' },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 15, paddingHorizontal: 15, paddingVertical: 12, marginBottom: 20, elevation: 1 },
  searchInput: { flex: 1, marginLeft: 10, fontFamily: 'Poppins_400Regular', color: COLORS.BLUE },
  heroContainer: { marginBottom: 25 },
  heroCard: { width: width - 40, height: 260, borderRadius: 35, overflow: 'hidden', elevation: 5 },
  heroImage: { width: '100%', height: '100%' },
  heroOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.05)', padding: 25, justifyContent: 'center', zIndex: 10 },
  heroPanel: { backgroundColor: 'rgba(12, 28, 48, 0.75)', padding: 22, borderRadius: 28, alignSelf: 'flex-start', maxWidth: '85%', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)', elevation: 10, zIndex: 15 },
  heroCityRow: { flexDirection: 'row', alignItems: 'center' },
  heroCity: { color: '#FFF', fontSize: 11, fontFamily: 'Poppins_700Bold', letterSpacing: 1.2, opacity: 0.9 },
  heroTitle: { color: '#FFF', fontSize: 22, fontFamily: 'Poppins_800ExtraBold', marginTop: 8, lineHeight: 26 },
  heroSubtitle: { color: '#FFF', fontSize: 11, fontFamily: 'Poppins_400Regular', marginTop: 10, opacity: 0.9, lineHeight: 16 },
  heroButton: { flexDirection: 'row', alignSelf: 'flex-start', backgroundColor: COLORS.YELLOW, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, marginTop: 18, alignItems: 'center', elevation: 3 },
  heroButtonText: { color: COLORS.BLUE, fontFamily: 'Poppins_700Bold', fontSize: 12, marginRight: 4 },
  heroDots: { flexDirection: 'row', gap: 8, justifyContent: 'center', marginTop: -35, zIndex: 20, paddingBottom: 15 },
  dotActive: { width: 18, height: 6, borderRadius: 3, backgroundColor: '#FFF' },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.4)' },

  // Guides
  guidesHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 },
  guidesTitle: { fontSize: 32, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE },
  flagLine: { flexDirection: 'row', width: 60, height: 4, marginTop: 5, borderRadius: 2, overflow: 'hidden' },
  flagColor: { flex: 1 },
  guideHeroCard: { height: 350, borderRadius: 35, overflow: 'hidden', marginBottom: 30, elevation: 5 },
  guideHeroImg: { width: '100%', height: '100%' },
  guideHeroContent: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.1)', padding: 25, justifyContent: 'flex-end' },
  pillExp: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.YELLOW, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, marginBottom: 12 },
  pillExpText: { fontSize: 10, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE, marginLeft: 5 },
  guideHeroName: { fontSize: 32, fontFamily: 'Poppins_800ExtraBold', color: '#FFF', lineHeight: 36 },
  guideHeroSub: { fontSize: 24, fontFamily: 'Poppins_600SemiBold', color: '#FFF', marginTop: -2 },
  guideHeroLoc: { flexDirection: 'row', alignItems: 'center', marginTop: 15 },
  guideHeroLocText: { fontSize: 13, fontFamily: 'Poppins_500Medium', color: '#FFF', marginLeft: 5 },
  ratingRowHero: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  guideHeroRate: { fontSize: 14, fontFamily: 'Poppins_500Medium', color: '#FFF' },
  reserveBtn: { flexDirection: 'row', alignSelf: 'flex-start', backgroundColor: COLORS.YELLOW, paddingHorizontal: 22, paddingVertical: 14, borderRadius: 20, marginTop: 25, alignItems: 'center', elevation: 5 },
  reserveBtnText: { color: COLORS.BLUE, fontFamily: 'Poppins_700Bold', fontSize: 15, marginLeft: 10 },
  guideRowCard: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 30, padding: 18, marginBottom: 18, alignItems: 'center', elevation: 3, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10 },
  guideRowImg: { width: 85, height: 85, borderRadius: 42.5 },
  guideRowContent: { flex: 1, marginLeft: 20 },
  guideRowName: { fontSize: 16, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE },
  guideRowPill: { alignSelf: 'flex-start', backgroundColor: '#F3E5F5', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12, marginTop: 5 },
  guideRowPillText: { fontSize: 11, fontFamily: 'Poppins_600SemiBold', color: '#9C27B0' },
  langRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  langTag: { fontSize: 10, fontFamily: 'Poppins_700Bold', color: COLORS.TEXT_MUTED, backgroundColor: COLORS.GRAY_LIGHT, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  ratingRowSmall: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  ratingValueSmall: { fontSize: 11, fontFamily: 'Poppins_600SemiBold', color: COLORS.TEXT_MUTED, marginLeft: 5 },
  guidePriceArea: { alignItems: 'flex-end', justifyContent: 'center' },
  guidePriceVal: { fontSize: 18, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE },
  guidePriceSub: { fontSize: 10, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, marginBottom: 8 },

  catRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 25, marginTop: 10 },
  catItem: { alignItems: 'center', width: '22%' },
  catIcon: { width: 64, height: 64, borderRadius: 32, justifyContent: 'center', alignItems: 'center', marginBottom: 8, elevation: 4, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 5 },
  catLabel: { fontSize: 11, fontFamily: 'Poppins_600SemiBold', color: COLORS.BLUE, textAlign: 'center' },

  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  sectionTitle: { fontSize: 20, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE },
  seeAllText: { color: COLORS.BLUE, fontSize: 13, fontFamily: 'Poppins_600SemiBold' },
  horizList: { paddingBottom: 15 },
  card: { width: 220, marginRight: 20, backgroundColor: '#FFF', borderRadius: 30, overflow: 'hidden', elevation: 3 },
  cardImage: { width: '100%', height: 160 },
  cardRating: { position: 'absolute', top: 15, left: 15, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.9)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10 },
  ratingValue: { fontSize: 11, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE, marginLeft: 4 },
  cardContent: { padding: 15 },
  cardTag: { alignSelf: 'flex-start', backgroundColor: COLORS.RED, paddingHorizontal: 10, paddingVertical: 2, borderRadius: 8, marginBottom: 8 },
  cardTagText: { color: '#FFF', fontSize: 9, fontFamily: 'Poppins_700Bold', textTransform: 'uppercase' },
  cardTitle: { fontSize: 17, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE },
  cardTagline: { fontSize: 11, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, marginTop: 4 },
  cardLocation: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  cardLocationText: { fontSize: 11, fontFamily: 'Poppins_500Medium', color: COLORS.BLUE, marginLeft: 5 },

  // Detail
  detailHero: { height: 400 },
  detailImage: { width: '100%', height: '100%' },
  detailHeaderAbs: { position: 'absolute', top: 50, left: 0, right: 0, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 20 },
  fabBack: { width: 45, height: 45, borderRadius: 22.5, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', elevation: 5, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 5 },
  detailContainer: { flex: 1, backgroundColor: COLORS.WHITE, marginTop: -35, borderTopLeftRadius: 40, borderTopRightRadius: 40, paddingHorizontal: 25, paddingTop: 15 },
  handle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#E0E0E0', alignSelf: 'center', marginBottom: 20 },
  detailLogoRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 10 },
  detailName: { fontSize: 24, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE, flex: 1, lineHeight: 30 },
  brandContainer: { alignItems: 'center' },
  detailBrandLogo: { width: 45, height: 45, resizeMode: 'contain' },
  brandText: { fontSize: 8, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE, marginTop: -5 },
  detailStars: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  detailRatingTxt: { fontSize: 15, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE, marginLeft: 8 },
  detailDesc: { fontSize: 13, fontFamily: 'Poppins_400Regular', color: '#455669', lineHeight: 20, marginTop: 12 },
  verMas: { color: '#3B82F6', fontFamily: 'Poppins_700Bold' },
  mapContainer: { marginTop: 20, marginBottom: 20 },
  mapCard: { height: 160, backgroundColor: '#F8FAFC', borderRadius: 25, borderWidth: 1, borderColor: '#F1F5F9', padding: 15, flexDirection: 'row', overflow: 'hidden' },
  mapInfo: { flex: 1, justifyContent: 'center' },
  mapPlaceName: { fontSize: 13, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE },
  mapPlaceSub: { fontSize: 11, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED },
  mapPlaceCity: { fontSize: 11, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED },
  mapGraphic: { flex: 1.5, position: 'relative' },
  mapLine: { position: 'absolute', width: '100%', height: 1, backgroundColor: '#E2E8F0', top: '50%', transform: [{ rotate: '-15deg' }] },
  mapPinContainer: { position: 'absolute', top: '40%', left: '40%' },
  landmark1: { position: 'absolute', top: '10%', right: '10%', alignItems: 'center' },
  landmark2: { position: 'absolute', bottom: '10%', right: '30%', alignItems: 'center' },
  landmarkTxt: { fontSize: 8, fontFamily: 'Poppins_500Medium', color: COLORS.TEXT_MUTED, textAlign: 'center' },
  factRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 },
  factItemCol: { flex: 1, alignItems: 'center' },
  factIconCircle: { width: 42, height: 42, borderRadius: 21, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  factLabelCol: { fontSize: 10, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE },
  factValueCol: { fontSize: 10, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, textAlign: 'center' },
  primaryBtnLarge: { flexDirection: 'row', backgroundColor: COLORS.YELLOW, borderRadius: 25, paddingVertical: 20, justifyContent: 'center', alignItems: 'center', marginTop: 30, elevation: 3 },
  primaryBtnText: { fontSize: 18, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE, marginRight: 15 },

  // Profile
  profileHero: { height: 280, position: 'relative' },
  profileArt: { width: '100%', height: 200, borderBottomLeftRadius: 40, borderBottomRightRadius: 40 },
  profileHeaderContent: { position: 'absolute', top: 50, left: 25, right: 25, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  profileHeaderTitle: { fontSize: 24, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE },
  settingsBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.8)', justifyContent: 'center', alignItems: 'center' },
  profilePhotoContainer: { position: 'absolute', bottom: 0, alignSelf: 'center', elevation: 10 },
  profileImage: { width: 120, height: 120, borderRadius: 60, borderWidth: 5, borderColor: COLORS.CREAM },
  badgeProfile: { position: 'absolute', bottom: 5, right: 5, width: 32, height: 32, borderRadius: 16, backgroundColor: COLORS.YELLOW, justifyContent: 'center', alignItems: 'center', borderWidth: 3, borderColor: COLORS.CREAM },
  profileInfo: { marginTop: 15, paddingHorizontal: 25, alignItems: 'center' },
  profileName: { fontSize: 24, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE },
  profileLevel: { fontSize: 14, fontFamily: 'Poppins_600SemiBold', color: '#6B4CFF', marginTop: 5 },
  statsPanel: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 25, paddingVertical: 18, paddingHorizontal: 30, width: '100%', marginTop: 25, elevation: 2 },
  statBox: { flex: 1, alignItems: 'center' },
  statVal: { fontSize: 20, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE },
  statLabelRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  statLabelText: { fontSize: 10, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, marginLeft: 4 },
  dividerV: { width: 1, height: '80%', backgroundColor: COLORS.GRAY_LIGHT, alignSelf: 'center' },
  achievements: { marginTop: 15, paddingBottom: 10 },
  achieveCard: { width: 160, borderRadius: 25, padding: 15, marginRight: 15, alignItems: 'center' },
  hexagon: { width: 60, height: 60, backgroundColor: '#FFF', borderRadius: 15, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  achieveTitle: { fontSize: 13, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE, textAlign: 'center' },
  achieveDesc: { fontSize: 10, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, textAlign: 'center', marginTop: 4 },
  profileMenu: { width: '100%', marginTop: 20, paddingBottom: 50 },
  menuRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 25, padding: 15, marginBottom: 15, elevation: 1 },
  menuIconBox: { width: 44, height: 44, borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
  menuTitle: { fontSize: 15, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE },
  menuSub: { fontSize: 11, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, marginTop: 2 },

  // Nav
  nav: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 90, backgroundColor: '#FFF', borderTopLeftRadius: 30, borderTopRightRadius: 30, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingBottom: 20, elevation: 20, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10 },
  navItem: { alignItems: 'center', paddingVertical: 8, paddingHorizontal: 15, borderRadius: 20 },
  navItemActive: { backgroundColor: COLORS.YELLOW },
  navLabel: { fontSize: 9, fontFamily: 'Poppins_500Medium', color: COLORS.TEXT_MUTED, marginTop: 4 },
  navLabelActive: { color: COLORS.BLUE, fontFamily: 'Poppins_700Bold' },

  // Common
  rowCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 25, padding: 12, marginBottom: 15, elevation: 1 },
  rowImg: { width: 70, height: 70, borderRadius: 20 },
  rowContent: { flex: 1, marginLeft: 15 },
  rowName: { fontSize: 16, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE },
  rowLoc: { fontSize: 11, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, marginTop: 2 },
  rowTag: { fontSize: 12, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_BLUE, marginTop: 4 },
  filters: { marginBottom: 20 },
  filterChip: { paddingHorizontal: 18, paddingVertical: 10, borderRadius: 20, backgroundColor: '#FFF', marginRight: 12, borderWidth: 1, borderColor: '#CBD8E5' },
  filterChipActive: { backgroundColor: COLORS.YELLOW, borderColor: COLORS.YELLOW },
  filterText: { fontSize: 12, fontFamily: 'Poppins_600SemiBold', color: COLORS.TEXT_MUTED },
  filterTextActive: { color: COLORS.BLUE },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', marginTop: 100 },
  emptyTitle: { fontSize: 18, fontFamily: 'Poppins_700Bold', color: COLORS.TEXT_MUTED, marginTop: 20 },
  emptyBtn: { backgroundColor: COLORS.BLUE, borderRadius: 20, paddingHorizontal: 25, paddingVertical: 12, marginTop: 20 },
  emptyBtnText: { color: '#FFF', fontFamily: 'Poppins_700Bold' },

  // Settings
  settingsHeader: { flexDirection: 'row', alignItems: 'center', marginTop: 30, marginBottom: 20 },
  backBtnSmall: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', elevation: 2 },
  settingsHeaderTitle: { fontSize: 22, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE, marginLeft: 15 },
  settingsSectionLabel: { fontSize: 14, fontFamily: 'Poppins_700Bold', color: COLORS.TEXT_MUTED, marginTop: 20, marginBottom: 10, marginLeft: 5 },
  settingsCard: { backgroundColor: '#FFF', borderRadius: 25, padding: 15, elevation: 1 },
  profileEditRow: { flexDirection: 'row', alignItems: 'center' },
  editAvatar: { width: 60, height: 60, borderRadius: 30 },
  editNameText: { fontSize: 16, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE },
  editSubText: { fontSize: 12, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED },
  editInput: { backgroundColor: COLORS.GRAY_LIGHT, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 5, fontFamily: 'Poppins_400Regular', color: COLORS.BLUE },
  settingToggleRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12 },
  settingIconContainer: { width: 36, height: 36, borderRadius: 12, backgroundColor: COLORS.GRAY_LIGHT, justifyContent: 'center', alignItems: 'center' },
  settingLabelText: { flex: 1, marginLeft: 15, fontSize: 14, fontFamily: 'Poppins_500Medium', color: COLORS.BLUE },
  settingsDivider: { height: 1, backgroundColor: COLORS.GRAY_LIGHT, marginLeft: 50 },
  toggleTrack: { width: 44, height: 22, borderRadius: 11, padding: 2 },
  toggleTrackActive: { backgroundColor: COLORS.BLUE },
  toggleTrackInactive: { backgroundColor: '#CBD8E5' },
  toggleKnob: { width: 18, height: 18, borderRadius: 9, backgroundColor: '#FFF' },
  toggleKnobActive: { alignSelf: 'flex-end' },
  toggleKnobInactive: { alignSelf: 'flex-start' },
  logoutBtnAction: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF', borderRadius: 20, paddingVertical: 15, marginTop: 30, borderWidth: 1, borderColor: COLORS.RED },
  logoutBtnText: { color: COLORS.RED, fontSize: 14, fontFamily: 'Poppins_700Bold', marginLeft: 10 },
  versionText: { textAlign: 'center', fontSize: 12, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, marginTop: 30 },

  // Routes
  routeInfoCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.BLUE, borderRadius: 20, padding: 15, marginBottom: 25 },
  routeInfoText: { color: COLORS.YELLOW, fontFamily: 'Poppins_600SemiBold', fontSize: 12, marginLeft: 10 },
  routeItemContainer: { flexDirection: 'row', marginBottom: 20, position: 'relative' },
  routeLine: { position: 'absolute', left: 14, top: 30, bottom: -20, width: 2, backgroundColor: '#CBD8E5', borderStyle: 'dashed' },
  routeStepIndicator: { width: 30, height: 30, borderRadius: 15, backgroundColor: COLORS.YELLOW, justifyContent: 'center', alignItems: 'center', zIndex: 2 },
  routeStepText: { fontSize: 12, fontFamily: 'Poppins_800ExtraBold', color: COLORS.BLUE },
  routeCard: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 25, padding: 12, marginLeft: 15, elevation: 2 },
  routeImg: { width: 60, height: 60, borderRadius: 15 },
  routeContent: { flex: 1, marginLeft: 15 },
  routeName: { fontSize: 14, fontFamily: 'Poppins_700Bold', color: COLORS.BLUE },
  routeLoc: { fontSize: 10, fontFamily: 'Poppins_400Regular', color: COLORS.TEXT_MUTED, marginTop: 2 },
  routeBadges: { flexDirection: 'row', gap: 6, marginTop: 6 },
  routeBadge: { backgroundColor: COLORS.GRAY_LIGHT, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  routeBadgeText: { fontSize: 8, fontFamily: 'Poppins_600SemiBold', color: COLORS.TEXT_BLUE },
  emptyIconContainer: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', elevation: 2, marginBottom: 20 }
})
